name: Preview HTML on Pull Requests
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Azure/docker-login@v1
      with:
        login-server: tbsacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - run: |
        docker build -f ./docker/Dockerfile . -t tbsacr.azurecr.io/covid-19-guidance:${{ github.sha }}
        docker push tbsacr.azurecr.io/covid-19-guidance:${{ github.sha }}
      
    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: tbs-prod-aks
        resource-group: tbs-prod-rg
        
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          kubernetes/covid-19-guidance-deployment.yml
          kubernetes/covid-19-guidance-service.yml
        images: |
          tbsacr.azurecr.io/covid-19-guidance:${{ github.sha }}
        namespace: |
          covid-19-guidance
